# Build and Push Hugo site to gh-pages
name: build-push

# trigger events
on:
  workflow_dispatch:

  push:
    branches:
      - "main"
    paths:
      - "src/**/*"

jobs:
  # Build & Push hugo site
  hugo:
    name: build-push
    if: ${{ github.repository == 'sujaykumarh-ansible/book' }}

    runs-on: ubuntu-latest
    steps:
      # Pull Source Code
      - name: âœ… Checkout Source
        uses: actions/checkout@v2

      - name: â¬‡ï¸ pull git submodules
        run: git submodule update --init --recursive

      - name: ğŸ”¨ Build Hugo Site
        run: |
          sh build.sh

      - name: â„¹ï¸ Setup files in dist
        run: |
          cp dist-readme.md src/dist/
          touch src/dist/.nojekyll
          if [ -f "CNAME" ]; then cp CNAME src/dist/CNAME; fi

      - name: ğŸš€ Push to gh-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: src/dist
          MESSAGE: "ğŸ”¨ Build gh-pages from {target-branch} {sha}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
